[package]
name = "sinq"
version = "0.1.0"
authors = ["jazzfool <saveuselon@gmail.com>", "Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"

[dependencies]
reclutch = { git = "https://github.com/jazzfool/reclutch" }
